image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  test: "SlowPochta.Tests"

before_script:
  - "cd src"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script: 
    - "cd $test"
    - "dotnet test"