image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  test: "SlowPochta.Tests"

before_script:
  - "cd src"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: test

test:
  stage: test
  script:
    - apt-get update 
    - apt-get install -y postgresql postgresql-client libpq-dev
    - psql -d template1
    - template1=# CREATE USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD' CREATEDB;
    - template1=# CREATE DATABASE "POSTGRES_DB" OWNER "$POSTGRES_USER";
    - template1=# \q
    - psql -U "POSTGRES_USER" -h localhost -d "POSTGRES_DB" -W
    - "cd $test"
    - "dotnet test"