image: microsoft/dotnet:latest

stages:
  #- build
  - test

variables:
  test: "SlowPochta.Tests"

before_script:
  - "cd src"
  - "dotnet restore"

# build:
#   stage: build
#   script:
#     - "dotnet build"

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: test

test:
  stage: test
  services:
  - postgres:9.6
  script:
    - service postgresql start
    - psql 
    - -U "POSTGRES_USER" -h postgres -d "POSTGRES_DB" -W
    - "cd $test"
    - "dotnet test"