image: microsoft/dotnet:latest

stages:
  - build
  - connect
  - test

variables:
  test: "SlowPochta.Tests"

before_script:
  - "cd src"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

services:
  - postgres:11

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: test

connect:
  image: postgres
  script:
  # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

test:
  stage: test
  script: 
    - "cd $test"
    - "dotnet test"