image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  test: "SlowPochta.Tests"

before_script:
  - "cd src"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: test

services:
  - postgres:9.6

test:
  stage: test
  script:
    - sudo service postgresql start
    - psql 
    - -U "POSTGRES_USER" -h postgres -d "POSTGRES_DB" -W
    - "cd $test"
    - "dotnet test"